services:
  app:
    image: ghcr.io/arzamaskov/run-app:app-${APP_TAG:-latest}
    env_file: [ /opt/run-app/app.env ]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  web:
    image: ghcr.io/arzamaskov/run-app:web-${WEB_TAG:-latest}
    ports:
      - "8081:80"
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    env_file: [ /opt/run-app/app.env ]
    environment:
      - POSTGRES_DB=${DB_DATABASE:-run_app_prod}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel}"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  queue:
    image: ghcr.io/arzamaskov/run-app:app-${APP_TAG:-latest}
    env_file: [ /opt/run-app/app.env ]
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  scheduler:
    image: ghcr.io/arzamaskov/run-app:app-${APP_TAG:-latest}
    env_file: [ /opt/run-app/app.env ]
    command: >
      sh -c "while true; do
        php artisan schedule:run --verbose --no-interaction &
        sleep 60
      done"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

